### ISSUE TITLE
Lose Settings on Reboot

### ISSUE THREAD

**Issue by dresnick** [DavidRogers/kato#1]
I've found that Kato loses its settings, whenever I reboot my computer, running Windows 7.  By "settings" I mean the Jenkins server and the specific projects that I want Kato to report on.  Is there a way to have Kato not lose its settings?

**Comment by Vall3n** [comment]
Kato is still losing settings for tracked projects every time you restart the app. It only remembers the server

Version 1.2.0.3 (about page)

**Comment by DavidRogers** [comment]
Thanks for the report, Ill look into it.

**Comment by Vall3n** [comment]
The issue here is that the C:\Users\{USER}\AppData\Local\Kato folder was not created, seems like the click-once application does not have the correct permissions. 

Creating the folder manually is a workaround.

**Comment by DavidRogers** [comment]
In https://github.com/DavidRogers/kato/commit/ed0fc08f4c42ef51d2d3d57244e264b5680b0a45 I made sure that settings are not saved if there is no internet connection.
