### ISSUE TITLE
Update frequency too quick

### ISSUE THREAD

**Issue by sharwell** [DavidRogers/kato#19]
When monitoring a large number of builds, this application is quite expensive with a polling interval of 10 seconds. It would be helpful to reduce the polling frequency, _especially_ in cases where a build for a job has not run in quite a while.

:bulb: I have a pull request ready to submit (currently blocked on #18) which increases the polling internal to 60 seconds across all projects.

**Comment by DavidRogers** [comment]
https://github.com/DavidRogers/kato/commit/ed0fc08f4c42ef51d2d3d57244e264b5680b0a45 should take care of this by allowing people to change the frequency.
