### ISSUE TITLE
Performance trouble when monitoring many builds

### ISSUE THREAD

**Issue by sharwell** [DavidRogers/kato#20]
I've observed that the application appears to hang periodically when monitoring a large number of builds.

:bulb: I have a pull request ready to submit (blocked on #18) which _dramatically_ improves performance through a combination of running operations in the background and submitting certain update requests in parallel. In this branch, I also disabled the WPF animation effect (set the animation time to 0) when hovering over list items, since this further improves the appearance of responsiveness in the application. I considered shortening but not eliminating the time, but when using the application over remote desktop it still appeared slow.

**Comment by ChrisMaddock** [comment]
@sharwell - Do you still have this around? I'm just looking at Kato for the first time. Everything fits what I'm after, except it seems to struggle with the number of builds we have. Would love to see this improved!

**Comment by DavidRogers** [comment]
https://github.com/DavidRogers/kato/commit/ed0fc08f4c42ef51d2d3d57244e264b5680b0a45 should take care of this as well.

**Comment by ChrisMaddock** [comment]
Great - thanks @DavidRogers!
