### ISSUE TITLE
Disabled builds should not affect overall status

### ISSUE THREAD

**Issue by sharwell** [DavidRogers/kato#21]
Currently if any build is disabled, the status icon in the tray shows the overall build status as disabled. It would be helpful if the overall build status only showed as disabled when _all_ selected builds are disabled.

:bulb: I have a pull request ready to submit (blocked on #18) which corrects this issue.

**Comment by DavidRogers** [comment]
@sharwell Do you have a PR ready for this? I'd love to review and merge it if you do!

**Comment by lanzelot1989** [comment]
Maybe it would be a good idea to make this configurable.

E.g. add a setting to "Include disabled builds in overall build status" and only mark the overall status as grey when the checkbox is enabled.
