### ISSUE TITLE
Update to add the color yellow for builds with the status of Warning

### ISSUE THREAD

**Issue by CStaplesLewis** [DavidRogers/kato#22]
Currently, if the build is flagged with a warning, it appears disabled (grey).

**Comment by tx99gtp** [comment]
I have addressed this with this pull request: https://github.com/DavidRogers/kato/pull/23

**Comment by CStaplesLewis** [comment]
Awsome! @DavidRogers any idea of a timing on a merge of this pull?

**Comment by DavidRogers** [comment]
Taking a look at it now!

**Comment by CStaplesLewis** [comment]
@DavidRogers I noticed you merged @tx99gtp [pull request ](https://github.com/DavidRogers/kato/pull/23), is there anyway to rebuild/distribute this fix?

**Comment by DavidRogers** [comment]
Done!
