### ISSUE TITLE
Improve font and background color in grid view for unstable builds

### ISSUE THREAD

**Issue by mippzon** [DavidRogers/kato#28]
When using matrix builds and building from unstable and the next build has built at least one unstable sub-job to the matrix, the grid block is yellow with white text. It's almost impossible to read the text. Would be nice to have the colors adjusted, at least for this scenario. I've attached an example.

![kato](https://cloud.githubusercontent.com/assets/2655379/22455564/a0cca332-e78d-11e6-9c79-3a43d6ccc322.PNG)

**Comment by DavidRogers** [comment]
In https://github.com/DavidRogers/kato/commit/ed0fc08f4c42ef51d2d3d57244e264b5680b0a45 I changed the color to a darker yellow...
