### ISSUE TITLE
Allow Kato to access secured Jenkins servers

### ISSUE THREAD

**Issue by pvandervelde** [DavidRogers/kato#3]
Our jenkins server is secured with a name / password (based on the Active Directory). It looks like Kato doesn't handle secured Jenkins instances. But no indication is given that there is a problem getting the data from the server and no ability to provide the username + password.

**Comment by DavidRogers** [comment]
This should be solved by https://github.com/DavidRogers/kato/pull/12. 
I just published a new version with this PR,you will have to uninstall/install the new version to get this update.
