### ISSUE TITLE
Removing added servers

### ISSUE THREAD

**Issue by mippzon** [DavidRogers/kato#32]
When a Jenkins server is added that doesn't work, it's not possible to remove it. Would be nice to have an option in the GUI to remove Jenkins servers. (If this information is stored somewhere, so I can manually remove it from config file/registry that would be nice to know as a workaround).

The main issue we are experiencing is that when installing from scratch, it will have a default server in the list (https://jenkins) which we cannot connect to. So we want to remove this one and replace with a working URL, since the not working one blocks fetching data from the working one.

**Comment by GDineen** [comment]
I've also got this problem. With the broken reference to http://jenkins the tray icon doesn't work and 'unable to connect to server' is stuck  on the dashboard

**Comment by mippzon** [comment]
We found a workaround for now: Go to %appdata%/Local and look for the Kato folder. In that there is a UserSettings.dat file. There you can remove unwanted servers, if you understand the syntax and structure of the file.

**Comment by DavidRogers** [comment]
This is a good suggestion, I'll see if I can make it happen sometime soon unless someone else wants to take a crack at it?

**Comment by JohnMcAvinue** [comment]
Can't find the Kato folder at all on my machine. I wouldn't consider this an enhancement - the application does not work when installed

**Comment by DavidRogers** [comment]
@JohnMcAvinue, The kato folder can be found => `%localappdata%\kato`. 
I am hoping to have time to work on this soon.

**Comment by MartinRoosKiel** [comment]
I have the problem, that there is noch kato folder in appdata.

Checked several times. Restarted and everything. I tried this on two different machines.

I am using windows 10.


Any suggestions?

**Comment by bnason-nf** [comment]
For whatever it's worth, I was having this same problem. To fix it, I copied version 1.0 from another machine that I had it installed on previously, and that works fine.

**Comment by DavidRogers** [comment]
Finally got around to fixing this! I will be publishing a new build of this later this week after I have tested it a bit more.
