### ISSUE TITLE
Add ability to ignore a build while keeping it in the dashboard

### ISSUE THREAD

**Issue by DavidRogers** [DavidRogers/kato#4]
This is mainly to make certain builds not show up in the status notifications, especially the tray icon.

**Comment by sharwell** [comment]
This is related to (but not a duplicate of) #21. I would find both helpful.

**Comment by DavidRogers** [comment]
This shouldn't be necessary now since #21 has been addressed in https://github.com/DavidRogers/kato/commit/ed0fc08f4c42ef51d2d3d57244e264b5680b0a45.
