### ISSUE TITLE
Unable to connect to Jenkins on non-default port

### ISSUE THREAD

**Issue by emilkaae** [DavidRogers/kato#9]
Hi,

When installing Kato with the clickonce installer, I am not able to connect to my build server on port 8080.

I was almost successful in building Kato locally on my windows 7 box, but there was a missing reference to Microsoft.Ui.Xaml apparently, that I do not have. Commenting out a single line gave me a version that could connect to the build server, so I suspect the latest binary release is slightly out of date?

/E

**Comment by DavidRogers** [comment]
Yes, they are out of sync a bit since my code cert expired and I haven't renewed it... I am not going to renew it either so I would suggest doing what you have done to make it work for you.

**Comment by DavidRogers** [comment]
This should be fixed by https://github.com/DavidRogers/kato/pull/6.
A new version has been published to the website (http://fieryjoy.com/kato).
You will have to uninstall and download/install the new version to get the update.
